version: '3'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=user
      - REDIS_PORT=6379
    restart: always
    networks:
      - prod
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    restart: always
    networks:
      - prod
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis

networks:
  prod:
    driver: bridge

volumes:
  redis-data:
    driver: local